import unittest
from unittest.mock import MagicMock, patch

from docubot import DocuBot, NOT_FOUND
from llm_client import GeminiClient


class TestAgenticWorkflow(unittest.TestCase):

    # fixtures

    def _make_bot(self, llm_client=None):
        # bypass __init__ so no docs/ folder is needed
        bot = DocuBot.__new__(DocuBot)
        bot.llm_client = llm_client
        bot.documents = [
            ("AUTH.md",          "Tokens are generated by generate_access_token in auth_utils.py."),
            ("AUTH.md",          "Clients must include the token in the Authorization header."),
            ("DATABASE.md",      "The users table contains user_id, email, password_hash, joined_at."),
            ("API_REFERENCE.md", "GET /api/users returns all users. Requires a valid token."),
        ]
        bot.index = bot.build_index(bot.documents)
        return bot

    def _make_llm(
        self,
        analyze_return="token auth",
        check_returns=None,
        reformulate_return="new search terms",
        answer_return="Here is the answer.",
    ):
        # check_returns is consumed in order across successive check_sufficiency calls
        if check_returns is None:
            check_returns = [(True, "SUFFICIENT: snippets cover the topic")]

        llm = MagicMock()
        llm.analyze_query.return_value = analyze_return
        llm.check_sufficiency.side_effect = check_returns
        llm.reformulate_query.return_value = reformulate_return
        llm.answer_from_snippets.return_value = answer_return
        return llm

    def _make_gemini_client(self):
        # patch genai so no real API key is needed
        with patch("llm_client.genai"):
            client = GeminiClient.__new__(GeminiClient)
            client.model = MagicMock()
            return client

    # _merge_snippets

    def test_merge_adds_to_empty(self):
        bot = self._make_bot()
        new = [("AUTH.md", "some snippet text here")]
        self.assertEqual(bot._merge_snippets([], new), new)

    def test_merge_deduplicates_same_snippet(self):
        bot = self._make_bot()
        snippet = ("AUTH.md", "token content that is long enough to test dedup logic ok")
        result = bot._merge_snippets([snippet], [snippet])
        self.assertEqual(result, [snippet])

    def test_merge_appends_new_snippet(self):
        bot = self._make_bot()
        s1 = ("AUTH.md",     "first snippet content here for dedup test")
        s2 = ("DATABASE.md", "second snippet content here for dedup test")
        self.assertEqual(bot._merge_snippets([s1], [s2]), [s1, s2])

    def test_merge_does_not_mutate_existing(self):
        bot = self._make_bot()
        existing = [("AUTH.md", "original content here for mutation test ok")]
        original_len = len(existing)
        bot._merge_snippets(existing, [("DATABASE.md", "new content here for mutation test ok")])
        self.assertEqual(len(existing), original_len)

    # _require_llm

    def test_require_llm_raises_without_client(self):
        bot = self._make_bot(llm_client=None)
        with self.assertRaises(RuntimeError):
            bot._require_llm("Test mode")

    def test_require_llm_silent_with_client(self):
        bot = self._make_bot(llm_client=MagicMock())
        bot._require_llm("Test mode")  # should not raise

    # answer_agentic — happy paths

    def test_single_pass_sufficient(self):
        # first retrieval is enough, loop exits immediately, no reformulation
        llm = self._make_llm(
            analyze_return="token auth",
            check_returns=[(True, "SUFFICIENT: snippets cover auth token creation")],
            answer_return="Tokens are generated by generate_access_token.",
        )
        bot = self._make_bot(llm_client=llm)

        result = bot.answer_agentic("Where is the auth token generated?")

        self.assertEqual(result, "Tokens are generated by generate_access_token.")
        llm.analyze_query.assert_called_once()
        llm.check_sufficiency.assert_called_once()
        llm.reformulate_query.assert_not_called()
        llm.answer_from_snippets.assert_called_once()

    def test_reformulates_on_insufficient_then_succeeds(self):
        # first pass insufficient, reformulates, second pass succeeds
        llm = self._make_llm(
            analyze_return="auth token",
            check_returns=[
                (False, "INSUFFICIENT: missing database query info"),
                (True,  "SUFFICIENT: now has auth and database context"),
            ],
            reformulate_return="users table database query",
            answer_return="Final combined answer.",
        )
        bot = self._make_bot(llm_client=llm)

        result = bot.answer_agentic("How do I authenticate and then query users?")

        self.assertEqual(result, "Final combined answer.")
        self.assertEqual(llm.check_sufficiency.call_count, 2)
        llm.reformulate_query.assert_called_once()
        llm.answer_from_snippets.assert_called_once()

    def test_generates_answer_after_max_iterations(self):
        # never sufficient, but still calls answer_from_snippets at the end
        llm = self._make_llm(
            check_returns=[
                (False, "INSUFFICIENT: missing info"),
                (False, "INSUFFICIENT: still missing"),
                (False, "INSUFFICIENT: still missing"),
            ],
            answer_return="Best-effort answer.",
        )
        bot = self._make_bot(llm_client=llm)

        result = bot.answer_agentic("Complex query", max_iterations=3)

        llm.answer_from_snippets.assert_called_once()
        self.assertEqual(result, "Best-effort answer.")

    def test_reformulate_called_between_passes_not_on_last(self):
        # 2 iterations both insufficient → reformulate called once, not twice
        llm = self._make_llm(
            check_returns=[
                (False, "INSUFFICIENT"),
                (False, "INSUFFICIENT"),
            ],
        )
        bot = self._make_bot(llm_client=llm)

        bot.answer_agentic("Some query", max_iterations=2)

        self.assertEqual(llm.reformulate_query.call_count, 1)

    # answer_agentic — edge cases

    def test_raises_without_llm_client(self):
        bot = self._make_bot(llm_client=None)
        with self.assertRaises(RuntimeError):
            bot.answer_agentic("Any query")

    def test_returns_not_found_when_retrieval_empty(self):
        # nothing retrieved → return NOT_FOUND, skip all further LLM calls
        llm = self._make_llm()
        bot = self._make_bot(llm_client=llm)
        bot.retrieve = MagicMock(return_value=[])

        result = bot.answer_agentic("Something completely unrelated")

        self.assertEqual(result, NOT_FOUND)
        llm.check_sufficiency.assert_not_called()
        llm.answer_from_snippets.assert_not_called()

    def test_deduplicates_snippets_across_passes(self):
        # same snippet on two passes should only appear once in the final call
        shared = ("AUTH.md", "Tokens are generated by generate_access_token in auth_utils.py.")
        llm = self._make_llm(
            check_returns=[
                (False, "INSUFFICIENT: needs more context"),
                (True,  "SUFFICIENT: now has enough"),
            ],
        )
        bot = self._make_bot(llm_client=llm)
        bot.retrieve = MagicMock(return_value=[shared])

        bot.answer_agentic("Where is the token generated?")

        snippets_passed = llm.answer_from_snippets.call_args[0][1]
        unique_count = len({(f, t[:50]) for f, t in snippets_passed})
        self.assertEqual(len(snippets_passed), unique_count)

    def test_analyze_query_result_used_for_first_retrieve(self):
        # the terms from analyze_query should drive the first retrieve call
        llm = self._make_llm(analyze_return="generate_access_token auth_utils")
        bot = self._make_bot(llm_client=llm)
        bot.retrieve = MagicMock(return_value=[("AUTH.md", "token info here for test ok")])

        bot.answer_agentic("Where is the token generated?")

        first_call_query = bot.retrieve.call_args_list[0][0][0]
        self.assertEqual(first_call_query, "generate_access_token auth_utils")

    # GeminiClient agentic methods

    def test_check_sufficiency_true_on_sufficient(self):
        client = self._make_gemini_client()
        client._generate = MagicMock(return_value="SUFFICIENT: auth topic fully covered")

        is_sufficient, reason = client.check_sufficiency("query", [("AUTH.md", "token info")])

        self.assertTrue(is_sufficient)
        self.assertIn("SUFFICIENT", reason.upper())

    def test_check_sufficiency_false_on_insufficient(self):
        client = self._make_gemini_client()
        client._generate = MagicMock(return_value="INSUFFICIENT: missing database details")

        is_sufficient, _ = client.check_sufficiency("query", [("AUTH.md", "token info")])

        self.assertFalse(is_sufficient)

    def test_analyze_query_returns_generate_output(self):
        client = self._make_gemini_client()
        client._generate = MagicMock(return_value="auth token, generate_access_token")

        result = client.analyze_query("Where is the auth token created?")

        self.assertEqual(result, "auth token, generate_access_token")

    def test_reformulate_query_returns_generate_output(self):
        client = self._make_gemini_client()
        client._generate = MagicMock(return_value="users table, database schema")

        result = client.reformulate_query(
            "How do I query users?",
            [("AUTH.md", "token info content here for test")],
            "INSUFFICIENT: missing database info",
        )

        self.assertEqual(result, "users table, database schema")

    def test_generate_wraps_api_error_as_runtime_error(self):
        client = self._make_gemini_client()
        client.model.generate_content.side_effect = Exception("network timeout")

        with self.assertRaises(RuntimeError) as ctx:
            client._generate("some prompt")

        self.assertIn("Gemini API call failed", str(ctx.exception))

    def test_format_context_renders_all_snippets(self):
        client = self._make_gemini_client()
        snippets = [
            ("AUTH.md",     "token creation info"),
            ("DATABASE.md", "users table schema"),
        ]

        context = client._format_context(snippets)

        for fname, text in snippets:
            self.assertIn(fname, context)
            self.assertIn(text, context)


if __name__ == "__main__":
    unittest.main()
